version: '3.8'

services:
  metrics-ai-engine:
    build: .
    container_name: metrics-ai-engine
    ports:
      - "8001:8001"
    environment:
      - PROMETHEUS_URL=http://prometheus:9090
      - OLLAMA_URL=http://ollama:11434
    volumes:
      - ./vector_store:/app/vector_store
    depends_on:
      - prometheus
      - ollama
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    restart: unless-stopped

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    restart: unless-stopped

volumes:
  prometheus_data:
  ollama_data:
